# Server properties
server:
  servlet:
    context-path: /actualidad-clima-api
  port: 8080
# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param
  profiles:
    active: dev
  application:
    name: actualidad-clima-api